{{- if .Values.secret.create }}
{{- $existingSecret := lookup "v1" "Secret" .Values.namespace .Values.secret.name }}
{{- if not $existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.secret.name }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret.stringData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}

