apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: {{ include "chart.fullname" . }}
spec:
  ports:
    - name: "{{ .Values.service.port }}"
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}

